blueprint:
  name: Zigbee2MQTT Smart Knob Media Volume Control
  description: Steuert Mediaplayer-Lautstärke mit einem Zigbee2MQTT Drehknopf
  domain: automation
  input:
    smartknob_device:
      name: Zigbee2MQTT Smart Knob Device
      description: Geräte-ID des Smart Knobs
      selector:
        device:
          integration: zigbee2mqtt
          model: "ERS-10TZBVK-AA"  # Für Frient Smart Knob
          # Für andere Modelle anpassen oder entfernen
    media_player:
      name: Media Player Entity
      description: Zu steuernder Media Player
      selector:
        entity:
          domain: media_player
    volume_step:
      name: Volume Step
      description: Lautstärkeänderung pro Klick (1-10)
      default: 5
      selector:
        number:
          min: 1
          max: 10
          step: 1
    press_action:
      name: Knopfdruck Aktion
      description: Aktion bei Knopfdruck
      default: play_pause
      selector:
        select:
          options:
            - play_pause
            - mute
            - none
          mode: dropdown

trigger:
  - platform: mqtt
    topic: "zigbee2mqtt/{{ device.name }}/action"
    payload: "rotate_left"
    value_template: "{{ value_json.action }}"
    id: rotate_left
  - platform: mqtt
    topic: "zigbee2mqtt/{{ device.name }}/action"
    payload: "rotate_right"
    value_template: "{{ value_json.action }}"
    id: rotate_right
  - platform: mqtt
    topic: "zigbee2mqtt/{{ device.name }}/action"
    payload: "press"
    value_template: "{{ value_json.action }}"
    id: button_press

# Der Rest bleibt gleich wie in der vorherigen Version ...
