blueprint:
  name: Zigbee2MQTT Smart Knob Media Player Control
  description: Steuert die Lautstärke eines Media Players mit einem Zigbee2MQTT Smart Knob
  domain: automation
  input:
    smart_knob:
      name: Smart Knob
      description: Wähle den Zigbee2MQTT Smart Knob
      selector:
        entity:
          integration: mqtt
          domain: sensor
    media_player:
      name: Media Player
      description: Wähle den zu steuernden Media Player
      selector:
        entity:
          domain: media_player

trigger:
  - platform: state
    entity_id: !input smart_knob

action:
  - variables:
      action: "{{ trigger.to_state.state }}"
  - choose:
      - conditions:
          - "{{ action == 'rotate_right' }}"
        sequence:
          - service: media_player.volume_up
            target:
              entity_id: !input media_player
      - conditions:
          - "{{ action == 'rotate_left' }}"
        sequence:
          - service: media_player.volume_down
            target:
              entity_id: !input media_player
      - conditions:
          - "{{ action == 'single' }}"
        sequence:
          - service: media_player.volume_mute
            target:
              entity_id: !input media_player
            data:
              is_volume_muted: toggle
