blueprint:
  name: Moes Smart Knob Media Control
  description: Steuert Media-Player über den Moes Zigbee Smart Knob via Zigbee2MQTT
  domain: automation
  input:
    media_player_entity:
      name: Media Player Entity
      description: Der zu steuernde Media-Player
      selector:
        entity:
          domain: media_player
    smartknob_device:
      name: SmartKnob Device
      description: Das Moes Zigbee Smart Knob Gerät
      selector:
        device:
          manufacturer: Moes
          model: Zigbee Smart Knob

variables:
  VOLUME_STEP: 5  # Anpassbarer Volume-Schritt in Prozent

trigger:
  - platform: device
    domain: zigbee2mqtt
    device_id: !input smartknob_device
    type: action
    subtype: rotate_left
  - platform: device
    domain: zigbee2mqtt
    device_id: !input smartknob_device
    type: action
    subtype: rotate_right
  - platform: device
    domain: zigbee2mqtt
    device_id: !input smartknob_device
    type: action
    subtype: press
  - platform: device
    domain: zigbee2mqtt
    device_id: !input smartknob_device
    type: action
    subtype: press_and_hold

action:
  - choose:
      - conditions: "{{ trigger.type == 'action' and trigger.subtype == 'rotate_left' }}"
        sequence:
          - service: media_player.volume_down
            target:
              entity_id: !input media_player_entity
            data:
              volume_step: "{{ (VOLUME_STEP / 100)|float }}"
      - conditions: "{{ trigger.type == 'action' and trigger.subtype == 'rotate_right' }}"
        sequence:
          - service: media_player.volume_up
            target:
              entity_id: !input media_player_entity
            data:
              volume_step: "{{ (VOLUME_STEP / 100)|float }}"
      - conditions: "{{ trigger.type == 'action' and trigger.subtype == 'press' }}"
        sequence:
          - service: media_player.media_play_pause
            target:
              entity_id: !input media_player_entity
      - conditions: "{{ trigger.type == 'action' and trigger.subtype == 'press_and_hold' }}"
        sequence:
          - service: media_player.media_next_track
            target:
              entity_id: !input media_player_entity
    default: []
